# Generated by Django 4.2.5 on 2023-09-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('added', models.DateField(auto_created=True)),
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=52)),
                ('location', models.CharField(max_length=52)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('None IT', 'Non IT'), ('Mobile Phone', 'Mobile Phone')], max_length=102)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
